### ISSUE TITLE
רספונסיביות: ליצור תפריט המבורגר רספונסיבי

### ISSUE THREAD

**Issue by Drorka** [Maakaf/maakaf-temp#10]
כרגע יש תצוגה רספונסיבית של תוכן, אבל התפריט העליון לא רספונסיבי.
צריך לייצר רספונסיביות על ידי כפתור המבורגר שיפתח את התפריט בתצוגת מובייל.

איך זה נראה היום:
![image](https://github.com/Maakaf/maakaf-temp/assets/116891360/553a8018-bc6a-4df6-ab67-1d44209a5867)

איך זה צריך להיראות בגדול:
![image](https://github.com/Maakaf/maakaf-temp/assets/116891360/526791ad-4520-4f66-a643-fd0821fdf790)

**Comment by UrielOfir** [comment]
מעולה. תודה דרור על היוזמה!

**Comment by danirdd92** [comment]
הנושא טופל
