### ISSUE TITLE
Date format isn't in the correct order

### ISSUE THREAD

**Issue by orati1111** [Maakaf/maakaf-temp#100]
שמתי לב שבטבלה של הפרויקטים באתר הפורמט הוא בפורמט אמריקאי כלומר שנה\יום\חודש במקום שנה\חודש\יום
תמונה:
![image](https://github.com/Maakaf/maakaf-temp/assets/39468832/ec0e9fec-2920-462d-b324-e113d9577ca1)

חקרתי קצת את הקוד מקור ומצאתי בקובץ SortTable.tsx  בשורה 178 זה כן אמור להמיר לתאריך מקומי אבל לא עושה זאת.

![image](https://github.com/Maakaf/maakaf-temp/assets/39468832/ea039eae-06f1-4cb5-af94-7ed08c907584)
בקובץ FormattedDate.astro קיים פרמטר "he,il" בתוך הפונקציה, אולי חסר הפרמטר הזה?

![image](https://github.com/Maakaf/maakaf-temp/assets/39468832/e2e9a60e-0a62-4623-a373-a43d87b0ddef)

נ"ב
הוספתי את הפרמטר הזה לפונקציה וזה אכן סידר את הפורמט לפורמט מקומי
![image](https://github.com/Maakaf/maakaf-temp/assets/39468832/280154b8-e1a9-4dfa-912e-97e2512d6422)

השאלה היא האם זה היה מכוון או שזה אכן משהו שצריך לסדר?

**Comment by UrielOfir** [comment]
זה לא היה מכוון.
לשים אותך על האישיו הזה?

**Comment by orati1111** [comment]
> זה לא היה מכוון. לשים אותך על האישיו הזה?

כן
