### ISSUE TITLE
Main page links using hardcoded links for internal pages

### ISSUE THREAD

**Issue by orati1111** [Maakaf/maakaf-temp#101]
בקובץ index.astro שאחראי על העמוד שער של האתר , קיימים קישורים אשר מקודדים בצורה hardcoded ולא בצורה יחסית למקום הנוכחי.

![image](https://github.com/Maakaf/maakaf-temp/assets/39468832/1abd2cbb-22f6-4e76-8ab2-87518fca6d14)

ברוב המקומות האחרים באתר (למשל ממש כמה שורות למטה ) זה אכן מקודד בצורה יחסית

![image](https://github.com/Maakaf/maakaf-temp/assets/39468832/776489e6-86cf-4cce-938e-9629d5b2a6f5)

**Comment by orati1111** [comment]
כמו בissue הקודם
סידרתי את הקישור הראשון שאכן ישלח בצורה יחסית למקור
אבל כשניסיתי לסדר את הקישור השני באותה השיטה זה לא מוצא לי את הקובץ
השאלה היא האם יש בעיה בכך שהקובץ נמצא בתקיית אב שונה יחסית לindex.astro?
למשל en_projects נמצא בתוך pages/en/members (גם index.astro נמצא בPages) אבל he_mentoring_project נמצא בcontent/members
אשמח לעזרה בנושא

**Comment by UrielOfir** [comment]
לשים אותך על האישיו הזה?

**Comment by orati1111** [comment]
> לשים אותך על האישיו הזה?

כן אשמח
