### ISSUE TITLE
הוספת רשימה עם של הפרוייקטים בקהילה עם אפשרות קטלוג ומיון

### ISSUE THREAD

**Issue by Shmuel-Levinson** [Maakaf/maakaf-temp#22]
אני משער שאפשר לעשות עמוד נפרד לזה, כמו אחד הטאבים למעלה?

**Comment by danirdd92** [comment]
יש אפשרות בתוך אסטרו לייצר אינטגרציות לרכיבים של SPA כדי לייצר פונקציונליות כזאת. אתה רוצה?

**Comment by UrielOfir** [comment]
לא נראה לי. אני רוצה שכל המידע יהיה בתוך הריפו.

**Comment by Shmuel-Levinson** [comment]
בדיוק רציתי להתעניין אם מוכר לכם פתרון פשוט ליצירת דרופ-דאון או כפתור או משהו שיעשה מיון/סינון לפרויקטים (בתוך קובץ md)

**Comment by danirdd92** [comment]
זה לא התפקיד של MD לייצר פונקציונליות כזאת, כשמו כן הוא markdown.
אפשר לאכלס פונקציונליות כזו או אחרת מסביב לMD

**Comment by UrielOfir** [comment]
המשך הדיון באישיו #51
