### ISSUE TITLE
יצירת רכיב ריאקט להצגה של טבלאות באתר

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#27]
דרישות המשימה:
1. לימוד המערכת של astro.
2. להוסיף לפרוייקט JSON דמה שיהיה בו מידע שיוצג בטבלה.
3. להוסיף לפרוייקט אינטגרציה לריאקט
4. להתשמש ב
https://tanstack.com/table/v8
כדי לייצר טבלה ולייצר לך עיצוב.

**Comment by zivi5645** [comment]
It is still relevant to join the project?
If so the happy

**Comment by UrielOfir** [comment]
We have the table for the mentors project.
We do neet to use it also to show all the projects that we have in the cummunity.

> It is still relevant to join the project? If so the happy
