### ISSUE TITLE
יצירת קומפוננטה להצגה של טבלאות באתר

### ISSUE THREAD

**Issue by danirdd92** [Maakaf/maakaf-temp#28]
משימה זו נועדה לתת טבילת אש בתרומה לקוד פתוח.

## דרישות המשימה

1. הכירו באופן שיטחי לפחות את העבודה מול אסטרו.
   - ניתן לקרוא את הדקומנטציה [באתר](https://astro.build/)  או סירטוני הדרכה טובים שקיימים היום ביוטיוב בנושא.
   - בנוסף אפשר לדבר איתי @danirdd92  באופן אישי על מנת לקבל הדרכה על הפרויקט ואיך הוא בנוי.
 2. יש להוסיף לפרויקט קובץ JSON שיכיל את המידע אותו נרצה להציג בתוך הטבלה, יש לברר מול @UrielOfir איך הוא אמור להראות.
 3. יש להוסיף לפרויקט אינטגרציה של React/**Svelte**/**Solid** לבחירתכם, נא לעקוב אחרי [הדקומנטציה](https://docs.astro.build/en/guides/integrations-guide/) הרלוונטית
 4. נא לעשות שימוש בספריה הבאה עם הפריימוורק שבחרתם על מנת לבנות את רכיב הטבלה - [ TanStack Table](https://tanstack.com/table/v8)
    - עיצוב הטבלה יתבצע בעזרת [tailwindcss](https://tailwindcss.com/) עם תמיכה של [DaisyUI](https://daisyui.com/)

**Comment by galeindor** [comment]
אני על זה בשיתוף פעולה על שרה

**Comment by danirdd92** [comment]
הצמד PR עם כל העבודה עד כה עבור CR @galeindor
