### ISSUE TITLE
 הוספת תמיכה באנגלית באתר

### ISSUE THREAD

**Issue by galeindor** [Maakaf/maakaf-temp#38]
לקראת שיתוף פעולה עם חברה שתעזור ותפתור issues עלינו להוסיף תמיכה באנגלית ולהוסיף תוכן באנגלית
אקח על עצמי את המשימה להכין את הפרויקט מבחינת astro ומבנה האתר לקראת התמיכה באנגלית

**Comment by danirdd92** [comment]
תן בראש אלוף  🏆

**Comment by UrielOfir** [comment]
Do we have an estimated timeline for resolving this issue?

**Comment by galeindor** [comment]
> Do we have an estimated timeline for resolving this issue?

כרגע עברתי על מה שצריך לעשות , לא אצליח לשבת על זה השבת אבל באמונה שלמה אסיים בין ראשון לשני , אעדכן בהתאם להתקדמות שלי , בנתיים אם יש לך תרגום לאנגלית של התכנים הרלוונטים מוזמן לשתף אותי ואוסיף כחלק העבודה במקום תוכן פיקטיבי.

**Comment by UrielOfir** [comment]
I currently don't possess an English translation of the site's content,
which is not of utmost importance. What truly matters is establishing an
English infrastructure for the site, as there are volunteers from overseas
eager to assist with content creation.

**Comment by UrielOfir** [comment]
> > Do we have an estimated timeline for resolving this issue?
> 
> כרגע עברתי על מה שצריך לעשות , לא אצליח לשבת על זה השבת אבל באמונה שלמה אסיים בין ראשון לשני , אעדכן בהתאם להתקדמות שלי , בנתיים אם יש לך תרגום לאנגלית של התכנים הרלוונטים מוזמן לשתף אותי ואוסיף כחלק העבודה במקום תוכן פיקטיבי.

I currently don't possess an English translation of the site's content, which is not of utmost importance. What truly matters is establishing an English infrastructure for the site, as there are volunteers from overseas eager to assist with content creation.

**Comment by galeindor** [comment]
אשמח לסיוע ממי שמסוגל , אני כרגע מתקשה טיפה עם המחשבה של איך להעביר את ה lang שיהיה גלובלי ויאפשר החלפה של התוכן בצורה נכונה , המשימה דורשת הבנה עמוקה מאוד של אסטרו והיו לי מספר בעיות של העברת פרמטרים של השפה הרצויה בין המקומות השונים
