### ISSUE TITLE
תרגום טקסט לאנגלית

### ISSUE THREAD

**Issue by danirdd92** [Maakaf/maakaf-temp#41]
עכשיו שהושלם הפיצ'ר לתמיכה באנגלית יש צורך לארגן תרגום לטקסט, דאגנו לסמן כל טקסט בעברית בצורה ברורה לחיפוש נוח והחלפה

שמתי את המשימה עלייך @UrielOfir

**Comment by UrielOfir** [comment]
The work with GitStart is starting. I'm closing this tickect. We'll keep going on this issue with them.
