### ISSUE TITLE
טופס הרשמה לפרוייקטים חדשים

### ISSUE THREAD

**Issue by MiryamLevi** [Maakaf/maakaf-temp#45]
דף שיתווסף לאתר ובו טופס הרשמה לצרוף פרויקט חדש לקהילה

**Comment by MiryamLevi** [comment]
טיוטה של הדרישות למשימה:
* רשימת השדות עבור הטופס ומה יהיה סוג המשתנה בתוכן
* הטופס עצמו
* שליחה - לאן?
* אישור למייל לאחר קבלת הטופס
* מניעת כפילויות? דרכים ליצירת קשר?

**Comment by UrielOfir** [comment]
הזווית שלי:
1. מה שהכי חשוב זה:
   א. קישור לריפו של הפרוייקט בגיטהאב.
   ב. באיזו שפת תכנות הפרוייקט כתוב (כדי שנדע באיזו קטגוריה בדיסקורד לשים אותו).
   ג. מה השם של הפרוייקט בדיסקורד.
   ד. פרטי יצירת קשר עם המגיש של הטופס.
3. אני חשבתי על גוגל פורמס ואז המידע נאסף שם.

**Comment by MiryamLevi** [comment]
אלו פרטים הם חובה?

**Comment by UrielOfir** [comment]
חובה-
כל מה שרשמתי בסעיף 1. א-ב-ג-ד זה חובה.

**Comment by UrielOfir** [comment]
המשך הדיון באנגלית באישיו #50
