### ISSUE TITLE
Add 'Add Your Project' Form Page for Maintainers

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#50]
Maintainers of open source projects should have the ability to add their projects to the Ma'akaf open-source community. To facilitate this process, we need to create a new page on the website where maintainers can easily submit their project information.

This new page will include an embedded Google Form that maintainers can fill out. The form will collect essential details about their projects, such as project name, description, URL ect'. 
The submitted information will help the community evaluate and include the projects in the Ma'akaf open-source community.
This addition will streamline the project submission process and encourage more maintainers to participate in our community.

**Comment by mzsrtgzr2** [comment]
i'll do it
