### ISSUE TITLE
Add 'join our community' page

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#52]

**Comment by vimalsonara** [comment]
Hey is there any specific design for this page?

**Comment by UrielOfir** [comment]
The concept I had in mind when I created this issue was to introduce a member directory on the community website. This page could serve as a registration hub.

At a basic level, we can instruct members to submit their information in a JSON file, similar to what we've done for the list of mentors. Once we collect this data, we can create a dedicated page to display it in a tabular format, showcasing all our community members.

What do you think about this idea?

**Comment by UrielOfir** [comment]
Here is the page with the mentors list and instructions how to assign as a mentor (can be transalte to Englsih by Google translate):
https://maakaf.netlify.app/members/mentoring_project/

**Comment by vimalsonara** [comment]
Got it. Just let me know when to start work on this page. I will do it.

**Comment by UrielOfir** [comment]
I assigned you to this issue.

Please write here your plan before you start to code :)

**Comment by UrielOfir** [comment]
Hi @vimalsonara 
Do you have estimation when you will send a PR for this issue?

**Comment by vimalsonara** [comment]
Hi @UrielOfir,

I'm grateful for the trust in assigning this issue to me. However, my current workload prevents me from giving it the attention it deserves. I apologize for any inconvenience and appreciate your understanding.

**Comment by Senior-ai** [comment]
Heyo, just saw the issue - but can't see the aforementioned URL (https://maakaf.netlify.app/members/mentoring_project/) as it got deleted and most of the pages in the site are still blank. I think I can shoot my shot to add this page, going through all registered members and displaying them as circular pics with the initial letters. Regarding the registry of a new member - I assume we could just list a new member if he joined the discord server - as far as I know, we can fetch updates regarding the member count using the discord API

**Comment by UrielOfir** [comment]
It changed.
This is the correct one:
https://maakaf.netlify.app/members/he_mentoring_project/
