### ISSUE TITLE
תקלה במציאת מאמרים באנגלית

### ISSUE THREAD

**Issue by galeindor** [Maakaf/maakaf-temp#56]
במסגרת פתרון תקלה אתמול הוספתי את מבנה התקיות הבא:
![image](https://github.com/Maakaf/maakaf-temp/assets/73552373/cc8fb599-ecf2-4ecd-9cec-8e71af206d2a)

וכעת בעת טעינה של ה content המידע המופיע תחת content/en אינו מופיע בגלל הדרך שבה יצרנו collections ,
המשימה היא קודם כל להבין את מבנה הקוד ולראות איפה אנחנו משתמשים ב collections ולאחר מכן לעשות אחת משתי אפשרויות :
1. לאחד כל אחד מהם שיתפוס גם את newbies וגם את newbies/en ביחד ואז הקוד יסנן מה שרלוונטי
2. אולי ליצור שכפול של ה collections ככה שיהיה אחד בעברית ואחד באנגלית ואז צריך לשנות גם את הקוד המופיע תחת SideNav.astro בשביל לסנן בהתאם 

מוזמנים לפנות אליי לעזרה ובתקווה אהיה זמין לכך במהלך היום , נראה לי משימה שיכולה לעזור למישהו להכנס לקוד ולתרום :)

**Comment by danirdd92** [comment]
@galeindor לא הבנתי, אני טיפלתי בזה ביחד איתך וראינו שאנחנו מסננים תכנים לפי שפה
