### ISSUE TITLE
להוסיף תוכן מגוגל דוקס אל האתר

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#6]
הסבר על roles בשרת הדיסקורד של מעקב, צריך להופיע תחת חברים, זה הסבר איך להיות פעיל בקהילה-
https://docs.google.com/document/d/1ngrU9bBZvo8f3OaIK-wkEbfuMjm-8IwSnwUrBs6ZnOw/edit?usp=sharing

**Comment by IdoPeled8** [comment]
איפה באתר צריך להוסיף את התוכן?

**Comment by danirdd92** [comment]
![image](https://github.com/Maakaf/maakaf-temp/assets/15320627/d0c43c3d-107b-4ecc-8b22-e0bea824a300)

כל קבצי הMD יש להכניס ל`content` תחת הקטגוריה הרלוונטית.
בנוסף יש להוסיף כותרת עבור הקישור בפאנל הצדדי `בtitle`

**Comment by danirdd92** [comment]
@UrielOfir  @IdoPeled8 

תעדכנו כל מי שמצטרף או כותב תוכן
