### ISSUE TITLE
Improve the mentors table

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#61]

**Comment by orenSampson** [comment]
Please, Assign me to this task

**Comment by UrielOfir** [comment]
להוסיף עמודה של תגים, בה המנטורים יוכלו לכתוב באיזה נושאים הם יכולים לעזור. למשל:
ראיונות עבודה, פרונטאנד, בקאנד.

**Comment by Avior95** [comment]
Hi, I saw that it is a bit difficult to find the content related to mentors. Is it possible to open a new cell in the navigation bar for mentors? And I will be happy if you assign me to this task

**Comment by UrielOfir** [comment]
> Hi, I saw that it is a bit difficult to find the content related to mentors. Is it possible to open a new cell in the navigation bar for mentors? And I will be happy if you assign me to this task

@orenSampson is working on that.
Can you be in touch with him?

**Comment by Avior95** [comment]
yep Thanks

**Comment by Avior95** [comment]
oren gave me the task and explained it to me a bit, can you assign me to the task? @UrielOfir  @orenSampson
