### ISSUE TITLE
Add hebrew members page content

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#65]

**Comment by shanilitov** [comment]
הי אני אקח את האישו הזה.

**Comment by shanilitov** [comment]
כתבתי את העמוד, זה היה באמת פשוט...
אני אמורה לדאוג שהטקסט יהיה מימין לשמאל, או שיש עוד עיצוב על המודים שמסדר את זה?

**Comment by UrielOfir** [comment]
לתוכן בעברית באופן אוטומטי מוגדר יישור מימין לשמאל.

יהי מעולה אם תפתחי פול ריקווסט ונוכל ראות את הקוד / טקסט שכתבת ואז לאשר או לתקן אם צריך.
