### ISSUE TITLE
למרכז את הכפתורים בעמוד הבית

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#7]
זה לא נעים לעין ש sponsors וגם recruiters מיושרים לימין.

**Comment by IdoPeled8** [comment]
אשמח לטפל בבעיה :)

**Comment by Drorka** [comment]
@IdoPeled8 
קיבלת

**Comment by danirdd92** [comment]
@UrielOfir אשמח לפירוט הבעיה, אם יש לך מוק של איך היית רוצה שיראה הכי טוב
@IdoPeled8 צריך תמיד לקחת בחשבון מה קורה ברגע שמגדילים\מקטינים את המסך,
חווית צפייה שונה לחלוטין בין פלאפון ללאפטופ לנייח עם 1080 או 4K

**Comment by UrielOfir** [comment]
סתם שיפור עיצוב.
פשוט שההגדרה של הכפתורים תהיה מרכז השורה ולא יישור לימין.

**Comment by UrielOfir** [comment]
@danirdd92 
אפשר לסגור את האישיו הזה?

**Comment by danirdd92** [comment]
@UrielOfir You tell me, are you satisfied with the current visuals?

**Comment by UrielOfir** [comment]
כרגע לי המצב של הכפתורים נראה תקין. אז אני סוגר. אם נרצה לשפר את הכפתורים נפתח אישיו חדש.
