### ISSUE TITLE
 Enhance Table of Projects on Website - Sort, GitHub Integration, Filtering, and More

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#78]
## Overview
We're looking to continue improving the project table on our website to enhance user experience and provide more dynamic and useful information about community projects. Below are key areas for improvement and enhancement:

## Points for Improvement

1. **Sorting Column Indicator:** Currently, users can sort columns in the table by clicking on the column headers. To enhance user awareness, we propose adding a visual indicator, like an arrow icon, to columns that can be sorted. This will make it clear to users that they can sort the table by specific columns.

2. **GitHub Integration:** We aim to pull project information directly from GitHub, reducing manual data entry. The component should receive a link to the project's repository and its Discord channel. The rest of the information, such as project name, description, last commit date, stars, etc., should be dynamically fetched from GitHub.

3. **Filtering Option:** It would be great to provide users with the ability to filter the table. For instance, users might want to view projects only in a specific programming language. Adding filtering options will improve the usability of the table.

4. **Last Commit Date and Stars:** To provide more insights, we'd like to display the last commit date and the number of stars each project has.

5. **GitHub Short Descriptions:** We should consider adding short project descriptions from GitHub, offering users a quick overview.

We understand that tackling all these tasks at once might not be feasible. We'd like to discuss which tasks you're interested in starting with and if any of these improvements present technical challenges that need to be addressed.

Your input and guidance are highly valued in making these enhancements to our project table. Please share your thoughts and preferences on where to begin and any potential roadblocks you foresee. Thank you for your contributions to Ma'akaf!

**Comment by gitstart-maakaf** [comment]
@UrielOfir do you have any preferences about doing "GitHub Integration" part? Any specific library you want to use that gets the information from GithubAPI?

**Comment by UrielOfir** [comment]
> @UrielOfir do you have any preferences about doing "GitHub Integration" part? Any specific library you want to use that gets the information from GithubAPI?

No.
Anything that brings the data efficiently.
