### ISSUE TITLE
לסדר תפריט צד כמו באתרי דוקומנטציה

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#8]
למשל כמו באתר של דוקסי:
https://www.docsy.dev/docs/

**Comment by UrielOfir** [comment]
@danirdd92 
אפשר לסגור את האישיו הזה?

**Comment by danirdd92** [comment]
@UrielOfir  .למרות שיש אין לו עיצוב מוסדר וזה מחכה לדרורה. תשאיר פתוח עד שנהיה מרוצים מהנראות
אם זה לא מעניין אותך, מבחינה פונקציונאלית הוא תקין ועושה את העבודה יפה מאוד ואתה יכול לסגור.

**Comment by UrielOfir** [comment]
בינתיים משאיר פתוח. תודה על העדכון
